### PR TITLE
Add omero-cli-zarr submodule

### PR DESCRIPTION
**Pull request by will-moore**
See https://github.com/ome/omero-cli-zarr/pull/157#issuecomment-1853827176

### CODE REVIEW

**Review by joshmoore — APPROVED** [review]
:+1:

**Comment by will-moore** [comment]
Presumably this PR doesn't change anything (and there isn't a build to test it) so nothing happens until it's merged, right?

**Comment by joshmoore** [comment]
> Presumably this PR doesn't change anything (and there isn't a build to test it) so nothing happens until it's merged, right?

The merge build would have picked it up and "done the right thing".

**Comment by will-moore** [comment]
If I search recent build https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/342/console for `omero-cli-zarr` I see this PR was merged, but I don't see that it has made a merge build of omero-cli-zarr and pushed it to https://github.com/snoopycrimecop/omero-cli-zarr (since that is still 404)?

**Comment by joshmoore** [comment]
Hmmm... surprising. I would have thought it would have created it. But I didn't look into the snoopy repo at the time. Now it exists though, so all's well. Worst case, we merge these type of submodule additions proactively as here. :+1:

**Pull request merged**
