### PR TITLE
Add ome/omero-certificates

### PR DESCRIPTION
**Pull request by manics**
Add ome/omero-certificates

### CODE REVIEW

**Comment by sbesson** [comment]
Closing/reopening to launch Travis on the last commit.

**Comment by sbesson** [comment]
A few flake8 issues flagged by `omero-test-infra` 
```
./omero_certificates/certificates.py:61:80: E501 line too long (80 > 79 characters)
./tests/unit/test_certificates.py:40:80: E501 line too long (82 > 79 characters)
./tests/unit/test_certificates.py:65:80: E501 line too long (82 > 79 characters)
./tests/unit/test_certificates.py:73:80: E501 line too long (88 > 79 characters)
```

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by sbesson** [comment]
Fails Travis CI with

```
+ python setup.py sdist
/omero-certificates/.eggs/setuptools_scm-3.5.0-py3.6.egg/setuptools_scm/utils.py:145: UserWarning: 'git' was not found
...
Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
```

Semi-related, the limitations mentioned in the final warning capture the main concern I have had about using tag-based versioning in Python projects.

**Comment by joshmoore** [comment]
This is failing https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/403/console

Closing.

**Pull request closed without merging**
