### PR TITLE
Update master submodules

### PR DESCRIPTION
**Pull request by snoopycrimecop**
Repository: ome/omero-plugins
Already up-to-date.

Repository: ome/minimal-omero-client
Updating b4477b7..a13ca65
Previously merged:
  - PR 53 jburel 'bump gateway version'

Repository: ome/omero-cli-duplicate
Already up-to-date.

Repository: ome/omero-cli-render
Updating 78a35bf..2964004
Previously merged:
  - PR 43 sbesson 'Set rendering settings for inactive channels'
  - PR 40 will-moore 'Fix reactivate channels'
  - PR 41 will-moore 'Docs improvements'

Repository: ome/omero-figure
Updating 8ec37d4..e6feb04
Previously merged:
  - PR 393 jburel 'V431'
  - PR 392 will-moore 'changelog 4.3.1'
  - PR 391 will-moore 'figure json docs'
  - PR 388 jburel 'Version 431'
  - PR 387 jburel 'break utils.py'

Repository: ome/omero-fpbioimage
Already up-to-date.

Repository: ome/omero-gallery
Updating c467101..0fb61db
Previously merged:
  - PR 65 manics '3.3.2 changelog (IDR date)'
  - PR 64 manics 'IDR date: 2020'

Repository: ome/omero-iviewer
Updating a5d93bc..ac77409
Previously merged:
  - PR 331 will-moore 'Changelog_0.10.0'
  - PR 313 dependabot[bot] 'Bump acorn from 6.2.0 to 6.4.1'
  - PR 322 dependabot[bot] 'Bump websocket-extensions from 0.1.3 to 0.1.4'
  - PR 318 dependabot[bot] 'Bump jquery from 3.4.0 to 3.5.0'
  - PR 311 will-moore 'Roi query support'
  - PR 330 jburel 'fix link following re-organisation'
  - PR 325 will-moore 'Allow higher max zoom for Big images'
  - PR 328 manics 'Link image ID back to webclient'
  - PR 327 manics 'Link to usage guide'
  - PR 312 jburel 'Install node12'

Repository: ome/omero-mapr
Already up-to-date.

Repository: ome/omero-metadata
Already up-to-date.

Repository: ome/omero-parade
Already up-to-date.

Repository: ome/omero-prometheus-tools
Already up-to-date.

Repository: ome/omero-rois
Already up-to-date.

Repository: ome/omero-signup
Updating 6954716..f7ab159
Previously merged:
  - PR 13 mtbc 'Add linebreak in acknowledgement form.'
  - PR 12 joshmoore 'Display omeroweb versions rather than omero-py'

Repository: openmicroscopy/omero-test-infra
Already up-to-date.

Repository: ome/omero-upload
Already up-to-date.

Repository: ome/omero-virtual-microscope
Already up-to-date.

Repository: openmicroscopy/omero-weberror
Already up-to-date.

Repository: openmicroscopy/omero-webtest
Already up-to-date.

Repository: ome/rOMERO-gateway
Already up-to-date.

Repository: ome/scripts
Updating cd74e00..5a2c392
Previously merged:
  - PR 170 will-moore 'ROI export handle points whitespace'

Generated by build [OMERO-PLUGINS-submodules#495](https://ci.openmicroscopy.org/job/OMERO-PLUGINS-submodules/495/).

----
--no-rebase

### CODE REVIEW

**Comment by sbesson** [comment]
Interestingly the `iviewer` job has been reproducibly failing with

```
     [exec] For more info visit https://webpack.js.org/guides/code-splitting/
     [exec] 16 07 2020 01:34:44.219:INFO [launcher]: Starting browser ChromeHeadless
     [exec] 16 07 2020 01:34:44.392:ERROR [karma-server]: UnhandledRejection
```

but https://travis-ci.org/github/ome/omero-iviewer/builds/707946662 is passing with almost the same configuration. I was not able to identify what differed in between the two environments. Any thought @will-moore @jburel ?

**Comment by will-moore** [comment]
Typically this could be due to Node.js versions on the different machines. JM may know more details.

**Comment by jburel** [comment]
I don't think the Karma server has started leading to the error.

**Comment by jburel** [comment]
@will-moore The version of Node.js is the same in both cases i.e. 12.x as far as I can tell

**Comment by jburel** [comment]
Actually I was not correct
```
ou can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
     [exec] For more info visit https://webpack.js.org/guides/code-splitting/
     [exec] 16 07 2020 09:08:52.869:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
     [exec] 16 07 2020 09:08:52.871:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
     [exec] 16 07 2020 09:08:52.913:INFO [launcher]: Starting browser ChromeHeadless
     [exec] 16 07 2020 09:08:53.146:ERROR [karma-server]: UnhandledRejection
     [exec] Result: 1
```
So it is something else

**Comment by will-moore** [comment]
Is this just a build of iviewer that is failing, or some integration tests?
Don't even know what the `Karma Server` is or what's running `ChromeHeadlessNoSandbox`?!

**Comment by jburel** [comment]
@will-moore it is for running the unit tests, the build is fine

**Comment by jburel** [comment]
error is due to the setup. This is the error when running the tests
```
no such file or directory, stat '/omero-iviewer/.omero'] {
     [exec]   errno: -2,
     [exec]   code: 'ENOENT',
     [exec]   syscall: 'stat',
     [exec]   path: '/omero-iviewer/.omero'
```

**Pull request merged**
