### PR TITLE
Remove Travis CI

### PR DESCRIPTION
**Pull request by sbesson**
As GitHub workflows have been set up at the individual repository level with a cron configuration, the top-level testing becomes unncessary

### CODE REVIEW

**Comment by sbesson** [comment]
Obviously GitHub actions are not activated on this repository yet so https://github.com/sbesson/omero-plugins/runs/1362764387 is the execution of the last commit on my own fork for anyone who would like to review this

**Comment by manics** [comment]
Do you anticipate the workflows being duplicated in each repo as well as in this one? If so could we add the scheduling to those individual jobs instead, and just have this repo as a way to group all plugins?

**Comment by sbesson** [comment]
> Do you anticipate the workflows being duplicated in each repo as well as in this one? If so could we add the scheduling to those individual jobs instead, and just have this repo as a way to group all plugins?

Am I correctly reading your proposal as:
- no GitHub workflow at the supermodule level 
- always include a schedule configuration in the main workflow for each submodule (and add to the workflows templates likely)

See also https://github.com/ome/ansible-roles/pull/40#issuecomment-721597872 for a related discussion arising timeouts. If the scheduling is migrated down to individual repos, the only remaining question from my side would be how to test coupled infra changes across N repos without creating N branches.

**Comment by manics** [comment]
> - no GitHub workflow at the supermodule level
> - always include a schedule configuration in the main workflow for each submodule (and add to the workflows templates likely)

Yes! Optionally we could have a workflow in this repo that verifies all submodules conform to those requirements, effectively a custom OME GH workflow linter.

How often are coupled PRs required across plugins? With the Ansible roles any coupling can be tested in the playbooks using the roles, such as IDR/deployment.

**Comment by sbesson** [comment]
> How often are coupled PRs required across plugins? With the Ansible roles any coupling can be tested in the playbooks using the roles, such as IDR/deployment.

I think it primarily happens when we made changes to the infrastructure component e.g. early days of omero-test-infra or looking at open changes, https://github.com/ome/omero-web/pull/224 tested across plugins or also https://github.com/ome/ansible-roles/pull/27 are changes we want to be widely tested across components. 

Frequency is largely occasional. If testing can happen elsewhere as you suggest, no objection from my side to dropping the  testing at the supermodule level.

**Comment by joshmoore** [comment]
Turning it off seems straight-forward enough. If we ever need any automation here, we can always turn on GHA. :+1:

**Pull request merged**
