### PR TITLE
Bump omero-test-infra to pin postgres to 9.6.13

### PR DESCRIPTION
**Pull request by joshmoore**
see: https://github.com/ome/omero-install/issues/212

### CODE REVIEW

**Comment by joshmoore** [comment]
Note: this may be a reason to either (a) automate submodule bumps for this repo or (b) to use `master` for test-infra.

**Comment by joshmoore** [comment]
Green! Surprisingly, _only_ iviewer failed in https://travis-ci.org/ome/omero-plugins/builds/554585209

Merging with https://github.com/ome/omero-plugins/issues/13 open for review.

**Comment by will-moore** [comment]
Iviewer is failing with 
```
     [exec] npm WARN karma-webpack@4.0.2 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
     [exec] npm WARN webpack-dev-middleware@3.7.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
     [exec] npm WARN ajv-errors@1.0.1 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.
...
...
     [exec] [91m05 07 2019 08:52:27.759:ERROR [preprocess]: [39mCan not load "webpack"!
     [exec]   TypeError: Cannot read property 'thisCompilation' of undefined
```
See https://github.com/webpack-contrib/karma-webpack/issues/365

**Comment by will-moore** [comment]
Tried fixing this at https://github.com/ome/omero-iviewer/pull/269 but no joy yet....

**Comment by will-moore** [comment]
PR at https://github.com/ome/omero-iviewer/pull/269 has Travis green again, so when that is merged, we can remove iviewer from ```allow_failures```

**Pull request merged**
